### ISSUE TITLE
ValueError: Dimensions must be equal, but... - IXI_HH_sex_classification_resnet

### ISSUE THREAD

**Issue by FilipaMarques** [DLTK/DLTK#48] opened 2019-08-28 15:51 UTC
I have been experiencing with (https://github.com/DLTK/DLTK/tree/master/examples/applications/IXI_HH_sex_classification_resnet), I made all the changes necessary in both reader.py and train.py in order to run both my .csv and my .nii images and it was going great. Then I realized I had the option 'extract_examples' as True in reader_params in train.py, since I want my 3D network to be trained on the full images I switched it to False and now I am having a "dimensions problem".

I have CT scans with dimensions [X, 512,512] where X, the number of slices, can be any number between 400 and 800. The message preceding code exit 1 is the following (happens during the 1st image):

> WARNING:tensorflow:From C:\Users\Utilizador\Anaconda3\envs\TesePython36\lib\site-packages\dltk\networks\regression_classification\resnet.py:77: conv3d (from tensorflow.python.layers.convolutional) is deprecated and will be removed in a future version.
> Instructions for updating:
> Use keras.layers.conv3d instead.
> WARNING:tensorflow:From C:\Users\Utilizador\Anaconda3\envs\TesePython36\lib\site-packages\dltk\core\residual_unit.py:71: max_pooling3d (from tensorflow.python.layers.pooling) is deprecated and will be removed in a future version.
> Instructions for updating:
> Use keras.layers.max_pooling3d instead.
> WARNING:tensorflow:From C:\Users\Utilizador\Anaconda3\envs\TesePython36\lib\site-packages\dltk\core\residual_unit.py:80: batch_normalization (from tensorflow.python.layers.normalization) is deprecated and will be removed in a future version.
> Instructions for updating:
> Use keras.layers.batch_normalization instead.
> Traceback (most recent call last):
>   File "C:\Users\Utilizador\Anaconda3\envs\TesePython36\lib\site-packages\tensorflow\python\framework\ops.py", line 1659, in _create_c_op
>     c_op = c_api.TF_FinishOperation(op_desc)
> tensorflow.python.framework.errors_impl.InvalidArgumentError: Dimensions must be equal, but are 63 and 62 for 'unit_3_0/sub_unit_add/add' (op: 'Add') with input shapes: [?,63,64,64,128], [?,62,64,64,128].
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "C:/Users/Utilizador/PycharmProjects/TesePython36/main.py", line 211, in <module>
>     steps=EVAL_EVERY_N_STEPS)
>   File "C:\Users\Utilizador\Anaconda3\envs\TesePython36\lib\site-packages\tensorflow_estimator\python\estimator\estimator.py", line 358, in train
>     loss = self._train_model(input_fn, hooks, saving_listeners)
>   File "C:\Users\Utilizador\Anaconda3\envs\TesePython36\lib\site-packages\tensorflow_estimator\python\estimator\estimator.py", line 1124, in _train_model
>     return self._train_model_default(input_fn, hooks, saving_listeners)
>   File "C:\Users\Utilizador\Anaconda3\envs\TesePython36\lib\site-packages\tensorflow_estimator\python\estimator\estimator.py", line 1154, in _train_model_default
>     features, labels, model_fn_lib.ModeKeys.TRAIN, self.config)
>   File "C:\Users\Utilizador\Anaconda3\envs\TesePython36\lib\site-packages\tensorflow_estimator\python\estimator\estimator.py", line 1112, in _call_model_fn
>     model_fn_results = self._model_fn(features=features, **kwargs)
>   File "C:/Users/Utilizador/PycharmProjects/TesePython36/main.py", line 63, in model_fn
>     kernel_regularizer=tf.contrib.layers.l2_regularizer(1e-3))
>   File "C:\Users\Utilizador\Anaconda3\envs\TesePython36\lib\site-packages\dltk\networks\regression_classification\resnet.py", line 95, in resnet_3d
>     mode=mode)
>   File "C:\Users\Utilizador\Anaconda3\envs\TesePython36\lib\site-packages\dltk\core\residual_unit.py", line 120, in vanilla_residual_unit_3d
>     x += orig_x
>   File "C:\Users\Utilizador\Anaconda3\envs\TesePython36\lib\site-packages\tensorflow\python\ops\math_ops.py", line 812, in binary_op_wrapper
>     return func(x, y, name=name)
>   File "C:\Users\Utilizador\Anaconda3\envs\TesePython36\lib\site-packages\tensorflow\python\ops\gen_math_ops.py", line 375, in add
>     "Add", x=x, y=y, name=name)
>   File "C:\Users\Utilizador\Anaconda3\envs\TesePython36\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 788, in _apply_op_helper
>     op_def=op_def)
>   File "C:\Users\Utilizador\Anaconda3\envs\TesePython36\lib\site-packages\tensorflow\python\util\deprecation.py", line 507, in new_func
>     return func(*args, **kwargs)
>   File "C:\Users\Utilizador\Anaconda3\envs\TesePython36\lib\site-packages\tensorflow\python\framework\ops.py", line 3300, in create_op
>     op_def=op_def)
>   File "C:\Users\Utilizador\Anaconda3\envs\TesePython36\lib\site-packages\tensorflow\python\framework\ops.py", line 1823, in __init__
>     control_input_ops)
>   File "C:\Users\Utilizador\Anaconda3\envs\TesePython36\lib\site-packages\tensorflow\python\framework\ops.py", line 1662, in _create_c_op
>     raise ValueError(str(e))
> ValueError: Dimensions must be equal, but are 63 and 62 for 'unit_3_0/sub_unit_add/add' (op: 'Add') with input shapes: [?,63,64,64,128], [?,62,64,64,128].

It is my understanding that the network only takes some defined image sizes, problem is, even after reading the 2 papers referenced in the documentation, I still can't find this sizes.
I am using python 3.6.8, tensorflow 1.13.1 and dltk 0.2.1. Any idea how I can solve this?

Thank you!

**Comment by venkatesh20** [comment] 2019-08-28 18:07
just guessing the probable cause here, but since you set extract_examples to false, is it because your full image size is not divisible by the number of gpu's you have on your system (probably the last minibatch has an odd number of samples, and hence the error is being thrown)? Upon a cursory reading of the code, i see that extract_examples would make sure to use the same example_size for each run, adding padding as needed.

**Comment by mrajchl** [comment] 2019-09-03 19:43
Correct, the issue is that you cannot input examples with a varying number of dimensions. However, the error is raised because you do not input sizes which are repeatedly divisible by 2. In the unit above, because of your initial inputs, the network tries to add two tensors of different shapes. Make sure that your examples are of the correct shape (I assume here: [None, 64,64,64, CHANNELS].

Closing, as this is not an error of DLTK.

**Closed as completed by mrajchl** 2019-09-03 19:43 UTC
